import React from "react";
import "../styles/utilities.css";
import "../styles/homepage.css";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        {/* bootstrap css */}
        <link
          rel="stylesheet"
          href="/bootstrap.min.css"
        />

        {/* google font */}
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />

        {/* AOS animation */}
        <link
          rel="stylesheet"
          href="https://unpkg.com/aos@2.3.1/dist/aos.css"
        />
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

        {/* call bootstrap js */}
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        ></script>
      </Head>
      <body>
        <div id="root">{children}</div>
      </body>
    </>
  );
}